first commit
Evancel/lesson_5.1 pull request #1
Opened 2023-02-02 20:35 UTC by Evancel

2023-02-03 16:23 UTC, alekseykoshelev requested changes

2023-02-03 16:23 UTC, alekseykoshelev commented on src/Book.java
> +    public String authorToString(Author author){
Тут лучше убрать аргумент у метода, иначе это немного странно, я ведь могу передать сюда другого автора.

2023-02-03 16:23 UTC, alekseykoshelev commented on src/Main.java
> +        System.out.println("Harry Potter: " + harryPotter.getName() + " " + joanneRowling.getFirstName() + " " +
Тут можно сделать так `harryPotter.getAuthor().getFirstName()`. Вдруг объекта автора у нас нет)

2023-02-04 09:33 UTC, Evancel commented on src/Book.java
> +    public String authorToString(Author author){
Исправила, спасибо!

2023-02-05 16:42 UTC, merged